opt_out_usage

platform :ios do
  private_lane :ci_certificates do
    create_keychain(
      name: ENV['CI_KEYCHAIN_NAME'],
      password: ENV['CI_KEYCHAIN_PASSWORD'],
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      lock_when_sleeps: false
    )
    match(
      keychain_name: ENV['CI_KEYCHAIN_NAME'],
      keychain_password: ENV['CI_KEYCHAIN_PASSWORD'],
      readonly: true,
      shallow_clone: true,
      verbose: false,
      clone_branch_directly: true,
    )
  end

  private_lane :certificates do
    match(
      readonly: true,
      shallow_clone: true,
      verbose: false,
      clone_branch_directly: true,
    )
  end

  private_lane :build do
    # Run lane 'ci_certificates' or 'certificates' depends on the system we’re using
    ENV['CI'] ? ci_certificates : certificates

    cocoapods(
      repo_update: true,
      podfile: "./ios/Podfile"
    )

    # Build the MyAwesomeProject
    gym(
      scheme: 'MyAwesomeProject',
      workspace: './ios/MyAwesomeProject.xcworkspace',
      silent: true,
      clean: true,
      configuration: 'Development',
      output_directory: './fastlane/builds/',
      output_name: 'MyAwesomeProject.ipa',
      export_options: {
          method: "development",
          provisioningProfiles: {
              ENV['APP_IDENTIFIER'] => ENV["sigh_#{ENV['APP_IDENTIFIER']}_#{ENV['MATCH_TYPE']}_profile-name"],
          }
      },
    )
  end


  lane :buildAndShip do
    build
  end
end
