# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

platform :ios do
  private_lane :certificates do
    if ENV['CI']
      create_keychain(
          name: "ci_keychain",
          password: "123456",
          default_keychain: true,
          unlock: true,
          timeout: 3600,
          lock_when_sleeps: false
      )
      match(
          keychain_name: "ci_keychain",
          keychain_password: "123456",
          app_identifier: ENV['APP_IDENTIFIER'],
          type: ENV['MATCH_TYPE'],
          readonly: true,
          shallow_clone: true,
          verbose: false,
          clone_branch_directly: true,
        )
      else
        match(
          app_identifier: ENV['APP_IDENTIFIER'],
          type: ENV['MATCH_TYPE'],
          readonly: true,
          shallow_clone: true,
          verbose: false,
          clone_branch_directly: true,
        )
    end
  end

  private_lane :build do
    certificates

    gym(
      scheme: 'MyAwesomeProject',
      workspace: './ios/MyAwesomeProject.xcworkspace',
      silent: true,
      clean: true,
      # Development | Release
      configuration: 'Development',
      output_directory: './fastlane/builds/',
      output_name: 'MyAwesomeProject.ipa',
      export_options: {
          method: "development",
          provisioningProfiles: {
              "de.dermeer.van.fastlaneInActions" => ENV["sigh_de.dermeer.van.fastlaneInActions_development_profile-name"],
          }
      },
      disable_xcpretty: true,
    )
  end

  lane :beta do
    build
  end
end
