name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x]

    steps:
      # Update yarn to use the latest version
      - name: update-yarn
        uses: taichi/actions-package-update@master
        env:
          AUTHOR_EMAIL: john@example.com
          AUTHOR_NAME: John
          EXECUTE: "true"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          UPDATE_COMMAND: yarn
        with:
          args: upgrade --latest
      # Setup Node
      - name: Use node in version ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/checkout@v1
      # Build and Test
      - name: yarn install and test
        run: |
          yarn install
          yarn test
        env:
          CI: true
