name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x]
        ruby-version: [ '2.4.x']

    steps:
      # Setup Node
      - name: Use node in version ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/checkout@v1
      # Build and Test
      - name: yarn install and test
        run: |
          yarn install
          yarn test
        env:
          CI: true
      # Setup ruby
      - name: Setup ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
        run: ruby --version

