name: CI

on: [push]

jobs:
  build:
    runs-on: macOS-10.14

    strategy:
      matrix:
        node-version: [8.x]

    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/checkout@v1
      - name: Install dependencies, test and build React-Native-App
        run: |
          yarn install
          yarn test
          yarn ios:buildAndShip
        env:
          APP_IDENTIFIER: de.dermeer.van.fastlaneInActions
          URL_TO_FASTLANE_CERTIFICATES_REPO: ${{ secrets.URL_TO_FASTLANE_CERTIFICATES_REPO }}
          CI: true
          CI_KEYCHAIN_NAME: "CI_KEYCHAIN"
          CI_KEYCHAIN_PASSWORD: ${{ secrets.CI_KEYCHAIN_PASSWORD }}
