name: CI

on: [push]

jobs:
  build:
    runs-on: macOS-10.14

    strategy:
      matrix:
        node-version: [8.x]
        ruby-version: [ '2.4.x']

    steps:
      # Setup Node
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      # Setup ruby
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      # Setup fastlane
      - name: Setup Fastlane
        run: |
          gem install fastlane -NV
      # Setup Cocoapods
      - name: Setup Cocoapods
        run: |
          gem install cocoapods
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v1
      # Build and Test
      - name: Build & Test
        run: |
          ruby --version
          fastlane --version
          yarn install
          cd ios
          pod install
          cd ..
          fastlane ios beta
        env:
          CI: true
          NODE_BINARY: node
          APP_IDENTIFIER: org.reactjs.native.example.MyAwesomeProject
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
