name: CI

on: [push]

jobs:
  build:
    runs-on: macOS-10.14

    strategy:
      matrix:
        node-version: [8.x]

    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/checkout@v1
      - run: yarn install
      - run: yarn test
      env:
        APP_IDENTIFIER: de.dermeer.van.fastlaneInActions
